travis:
  secure:
    BINSTAR_TOKEN: b4Q94rysi3AjT6/ltIs0rrbacATAMRXTr4hL1FJt5V5J6bManAmbfpWRjZ2YZiESuzG7w0ASncnBE6UiugCcdUZacUsmEuTOkNb/WmnOFWvRqWHOIAyAbNO5TXgq60DxwABEVxhBNwURsGUKBXmDmGyD8UJ6qbqFJaW9n4mqXOCdM9LDDKOBVbv1WdalI2eXJy5XcFAw7UFGQttg6vAcxxkIPmHGpiEP+3ii5NurEBW9bCuyAVzJg270prO564puT//e/NUkPZRr1Klo1TQvcygwXDFHhH+JL10SGmU/cBf5p1AD1c/vCPR3XZfHGXR1ydIMOrZGRMTU/JnWH8nQQ47kGWNyKPI/H11SIzfUGlMYASfEzy53gmxFnHDTAzT/7gmyDJJLRSbHSG3TsFJjR0NF3P8T6lRCtORmmLlQZwYnOqmox2X7plY8hFgmyEKPZahJf20bC9/NFKdYfvnivWvbSXp3XpcJzkHVXmhVpQUGbYqJNHK35rdmmsUhbPXiDLZzZdUb6fqcgBaGuCeAlTDZ6ozwlH/4K4LCXgKkatgozANHb9/RZQXKhx/6JqG7p+N+cvkREJvV0LpX9B7kdUmqXW8XvuXUYzTFOA0gHGG95NuTNPnZTejPn+lzFPEwGicDHUerp6RN+pzwngRA6eyaD1C32MMn+l+o0sJ2atI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
